# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"openGzipOrText": "00_utils.ipynb",
         "iterDat": "01_readuniprot.ipynb",
         "datEntryLnsWithCode": "01_readuniprot.ipynb",
         "datEntryPrimaryAC": "01_readuniprot.ipynb",
         "scanDat": "01_readuniprot.ipynb",
         "allPrimaryACsInDat": "01_readuniprot.ipynb",
         "datEntryPE": "01_readuniprot.ipynb",
         "datEntryName": "01_readuniprot.ipynb",
         "datEntrySeq": "01_readuniprot.ipynb",
         "datEntryGOLines": "01_readuniprot.ipynb",
         "datEntryGOTermPresent": "01_readuniprot.ipynb",
         "datEntryIsAtpBinding": "01_readuniprot.ipynb",
         "datEntryIsGtpBinding": "01_readuniprot.ipynb",
         "datEntryIsMetalBinding": "01_readuniprot.ipynb",
         "datEntryKWs": "01_readuniprot.ipynb",
         "listIfStr": "01_readuniprot.ipynb",
         "filterDatEntry": "01_readuniprot.ipynb",
         "aaLetters": "01_readuniprot.ipynb",
         "aaLettersSet": "01_readuniprot.ipynb",
         "parseClustersFromUniref": "01_readuniprot.ipynb"}

modules = ["utils.py",
           "readuniprot.py"]

doc_url = "https://ikedim01.github.io/proteinscan/"

git_url = "https://github.com/ikedim01/proteinscan/tree/master/"

def custom_doc_links(name): return None
