# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"openGzipOrText": "00_utils.ipynb",
         "iterDat": "01_readuniprot.ipynb",
         "datEntryLnsWithCode": "01_readuniprot.ipynb",
         "datEntryPrimaryAC": "01_readuniprot.ipynb",
         "scanDat": "01_readuniprot.ipynb",
         "allPrimaryACsInDat": "01_readuniprot.ipynb"}

modules = ["utils.py",
           "readuniprot.py"]

doc_url = "https://ikedim01.github.io/proteinscan/"

git_url = "https://github.com/ikedim01/proteinscan/tree/master/"

def custom_doc_links(name): return None
