# AUTOGENERATED! DO NOT EDIT! File to edit: 01_readuniprot.ipynb (unless otherwise specified).

__all__ = ['iterDat']

# Cell

import gzip
import itertools

from proteinscan import utils

# Cell

def iterDat(datFPath) :
    """
    Iterator yielding a list of lines for each entry in the .dat file.
    """
    with utils.openGzipOrText(datFPath) as f :
        for (isEnd,it) in itertools.groupby(f, lambda ln : ln.strip()=='//') :
            if not isEnd :
                yield(list(it))