# AUTOGENERATED! DO NOT EDIT! File to edit: 00_utils.ipynb (unless otherwise specified).

__all__ = ['openGzipOrText']

# Cell

import gzip

# Cell

def openGzipOrText(fPath,encoding=None) :
    """Opens a file for reading as text, uncompressing it on read if the path ends in .gz"""
    if str(fPath).lower().endswith('.gz') :
        return gzip.open(fPath,'rt',encoding=encoding)
    else :
        return open(fPath,'rt',encoding=encoding)